# -*- coding: utf-8 -*-
"""DMML_Coursework.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kl9YTvD6cINv8pAaYSWlavhOL7nVIMCK

Part(A) - Loan Approval Status Prediction

Part(A)-Task(2) - Data Understanding: Producing Your Experimental Design

Statistical description
"""

import pandas as pd

df = pd.read_csv('/content/loan_approval_data.csv')

df.drop('id', axis=1, inplace=True)

df.drop('max_allowed_loan', axis=1, inplace=True)

df.drop('Credit_Application_Acceptance', axis=1, inplace=True)

df.head()

df.info()

df.describe(include='all')

df.isnull().sum()

df.duplicated().sum()

import matplotlib.pyplot as plt

df['loan_approval_status'].value_counts().plot(kind='bar')
plt.title('Ditribution of Loan Approval Status')
plt.xlabel('Status')
plt.ylabel('Count')
plt.show()

"""Variable scale type"""

df.dtypes

"""Part(A)-Task(3) - Data Preparation: Cleaning and Transforming your data

(b)

1. Age
"""

df['age'].head(5)

df['age'].dtype

df['age'].isnull().sum()

df['age'] = pd.to_numeric(df['age'], errors='coerce')

(df['age'] <= 0).sum()

(df['age'] > 100).sum()

df['age'].describe()

df.loc[df['age'] <= 0, 'age'] = None

df.loc[df['age'] > 100, 'age'] = None

df = df.dropna(subset=['age'])

df['age'] = df['age'].astype('int64')

df['age'].head(5)

df['age'].dtype

df['age'].isnull().sum()

(df['age'] <= 0).sum()

(df['age'] > 100).sum()

df['age'].describe()

"""2. Sex"""

df.columns

df['Sex'].value_counts(dropna=False).head(5)

df['Sex'].isnull().sum()

df.drop('Sex', axis=1, inplace=True)

df.columns

"""3. Education Qualification"""

df.columns

df['Education_Qualifications'].value_counts(dropna=False).head(10)

df['Education_Qualifications'].unique()

df["Education_Qualifications"].value_counts()['Unknown ']
+ df["Education_Qualifications"].value_counts()['Unknown']

df.drop('Education_Qualifications', axis=1, inplace=True)

df.columns

"""4. Home Ownership"""

df['home_ownership'].value_counts(dropna=False).head(5)

df['home_ownership'] = df['home_ownership'].astype(str).str.lower().str.strip()

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df['home_ownership'] = le.fit_transform(df['home_ownership'])

df['home_ownership'].value_counts().head(5)

"""5. Employment Length"""

df['emplyment_length'].describe()

df = df.dropna(subset=['emplyment_length'])

df = df[df['emplyment_length'] <= 100]

df['emplyment_length'].describe()

"""6. Loan Intent"""

df['loan_intent'].value_counts(dropna=False).head(10)

df['loan_intent'] = le.fit_transform(df['loan_intent'])

df['loan_intent'].value_counts().head(10)

"""7. Loan Interest Rate"""

(df['loan_interest_rate'] < 0).sum()

(df['loan_interest_rate'] > 100).sum()

df['loan_interest_rate'].describe()

df['loan_interest_rate'] = pd.to_numeric(df['loan_interest_rate'], errors='coerce')

df = df.dropna(subset=['loan_interest_rate'])

df = df[df['loan_interest_rate'] >= 0]

df = df[df['loan_interest_rate'] <= 100]

(df['loan_interest_rate'] < 0).sum()

(df['loan_interest_rate'] > 100).sum()

df['loan_interest_rate'].describe()

"""8. Payment Default on File"""

df['payment_default_on_file'].unique()

df['payment_default_on_file'].value_counts(dropna=False).head(6)

df['payment_default_on_file'].isnull().sum()

df = df.dropna(subset=['payment_default_on_file'])

df['payment_default_on_file'] = df['payment_default_on_file'].astype(str).str.lower().str.strip()

df['payment_default_on_file'] = df['payment_default_on_file'].replace({'y': 'yes', 'n': 'no'})

df['payment_default_on_file'] = le.fit_transform(df['payment_default_on_file'])

df['payment_default_on_file'].isnull().sum()

df['payment_default_on_file'].value_counts(dropna=False).head(6)

df['payment_default_on_file'].unique()

"""9. Loan Approval Status"""

df['loan_approval_status'].value_counts(dropna=False).head(10)

df['loan_approval_status'].isnull().sum()

df = df.dropna(subset=['loan_approval_status'])

df['loan_approval_status'] = df['loan_approval_status'].astype(str).str.lower().str.strip()

df['loan_approval_status'] = df['loan_approval_status'].replace({'accept': 'approved', 'declined': 'rejected', 'reject': 'rejected'})

df['loan_approval_status'] = le.fit_transform(df['loan_approval_status'])

df['loan_approval_status'].isnull().sum()

df['loan_approval_status'].value_counts(dropna=False).head(10)

"""10. Scaling all numeric variables"""

numeric_columns = ['age', 'income', 'emplyment_length', 'loan_amount', 'loan_interest_rate',
                   'loan_income_ratio', 'credit_history_length']

df[numeric_columns].describe().round(3)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df[numeric_columns] = scaler.fit_transform(df[numeric_columns])

df[numeric_columns].describe().round(3)

"""Part(A)-Task(4) - Modelling: Create Predictive Classification Models

(b)(i)
"""

x = df.drop('loan_approval_status', axis=1)
y = df['loan_approval_status']

print("Feature Names:\n", x.columns.tolist())

print("shape of x:", x.shape)
print("shape of y:", y.shape)

"""(b)(iv)"""

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y,
    test_size=0.2,
    random_state=14,     # ensures SAME test set for all models
    stratify=y           # ensures class ratio stays the same
)

print("Training class distribution:")
print(y_train.value_counts(normalize=True))

print("Testing class distribution:")
print(y_test.value_counts(normalize=True))

"""Part(A)-Task(5) - Evaluation: How good are your models

(a)

Training the models
"""

from sklearn.naive_bayes import GaussianNB

nb_model = GaussianNB()
nb_model.fit(x_train, y_train)

from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(x_train, y_train)

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(random_state=14)
rf_model.fit(x_train, y_train)

"""Creating the predictions"""

y_pred_nb = nb_model.predict(x_test)
y_pred_lr = lr_model.predict(x_test)
y_pred_rf = rf_model.predict(x_test)

"""Confusion matrices"""

from sklearn.metrics import confusion_matrix

print("\nNaive Bayes – Confusion Matrix")
print(confusion_matrix(y_test, y_pred_nb))

print("Logistic Regression – Confusion Matrix")
print(confusion_matrix(y_test, y_pred_lr))

print("Random Forest – Confusion Matrix")
print(confusion_matrix(y_test, y_pred_rf))

"""(b)"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report

print("Naive Bayes – Accuracy:", round(accuracy_score(y_test, y_pred_nb), 3))
print("Naive Bayes – AUC-ROC:", round(roc_auc_score(y_test, y_pred_nb), 3))
print(classification_report(y_test, y_pred_nb))

print("Logistic Regression – Accuracy:", round(accuracy_score(y_test, y_pred_lr), 3))
print("Logistic Regression – AUC-ROC:", round(roc_auc_score(y_test, y_pred_lr), 3))
print(classification_report(y_test, y_pred_lr))

print("Random Forest – Accuracy:", round(accuracy_score(y_test, y_pred_rf), 3))
print("Random Forest – AUC-ROC:", round(roc_auc_score(y_test, y_pred_rf), 3))
print(classification_report(y_test, y_pred_rf))

"""(d)"""

print("RF Train Accuracy:", round(rf_model.score(x_train, y_train), 3))
print("RF Test Accuracy:", round(rf_model.score(x_test, y_test), 3))

"""(e)"""

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [10, 20, None]}

grid = GridSearchCV(
    estimator = RandomForestClassifier(random_state=14),
    param_grid = param_grid,
    scoring = 'f1_macro',
    cv = 10,
    n_jobs = -1)

"""(e)(i)"""

grid.fit(x_train, y_train)

"""(e)(ii)"""

print("Best Parameters:", grid.best_params_)

"""(e)(iii)"""

rf_best = grid.best_estimator_
y_pred_best = rf_best.predict(x_test)

print("Original RF Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))

from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay

print("Original RF Confusion Matrix:")
RF_CM = confusion_matrix(y_test, y_pred_rf)
disp=ConfusionMatrixDisplay(confusion_matrix=RF_CM,display_labels = rf_best.classes_)
disp.plot()

print("Tuned RF Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_best))

print("Tuned RF Confusion Matrix:")
RF_CM_best = confusion_matrix(y_test, y_pred_best)
disp=ConfusionMatrixDisplay(confusion_matrix=RF_CM_best,display_labels = rf_best.classes_)
disp.plot()

"""(e)(iv)"""

from sklearn.metrics import classification_report, roc_auc_score

print("Original RF Classification Report:")
print(classification_report(y_test, y_pred_rf))
print("Original RF AUC:", round(roc_auc_score(y_test, y_pred_rf), 3))

print("Tuned RF Classification Report:")
print(classification_report(y_test, y_pred_best))
print("Tuned RF AUC:", round(roc_auc_score(y_test, y_pred_best), 3))

"""Part(B) - Maximum Loan Amount Prediction"""

df_partb = pd.read_csv("/content/loan_approval_data.csv")

df_partb.drop('id', axis=1, inplace=True)
df_partb.drop('Credit_Application_Acceptance', axis=1, inplace=True)

df_partb['age'] = pd.to_numeric(df_partb['age'], errors='coerce')
df_partb.loc[df_partb['age'] <= 0, 'age'] = None
df_partb.loc[df_partb['age'] > 100, 'age'] = None
df_partb = df_partb.dropna(subset=['age'])
df_partb['age'] = df_partb['age'].astype('int64')

df_partb.drop('Sex', axis=1, inplace=True)

df_partb.drop('Education_Qualifications', axis=1, inplace=True)

df_partb['home_ownership'] = df_partb['home_ownership'].astype(str).str.lower().str.strip()

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_partb['home_ownership'] = le.fit_transform(df_partb['home_ownership'])

df_partb = df_partb.dropna(subset=['emplyment_length'])
df_partb = df_partb[df_partb['emplyment_length'] <= 100]

df_partb['loan_intent'] = le.fit_transform(df_partb['loan_intent'])

df_partb['loan_interest_rate'] = pd.to_numeric(df_partb['loan_interest_rate'], errors='coerce')
df_partb = df_partb.dropna(subset=['loan_interest_rate'])
df_partb = df_partb[df_partb['loan_interest_rate'] >= 0]
df_partb = df_partb[df_partb['loan_interest_rate'] <= 100]

df_partb = df_partb.dropna(subset=['payment_default_on_file'])
df_partb['payment_default_on_file'] = df_partb['payment_default_on_file'].astype(str).str.lower().str.strip()
df_partb['payment_default_on_file'] = df_partb['payment_default_on_file'].replace({'y': 'yes', 'n': 'no'})
df_partb['payment_default_on_file'] = le.fit_transform(df_partb['payment_default_on_file'])

df_partb = df_partb.dropna(subset=['loan_approval_status'])
df_partb['loan_approval_status'] = df_partb['loan_approval_status'].astype(str).str.lower().str.strip()
df_partb['loan_approval_status'] = df_partb['loan_approval_status'].replace({'accept': 'approved', 'declined': 'rejected', 'reject': 'rejected'})
df_partb['loan_approval_status'] = le.fit_transform(df_partb['loan_approval_status'])

df_partb['max_allowed_loan'] = pd.to_numeric(df_partb['max_allowed_loan'], errors='coerce')
df_partb.loc[df_partb['max_allowed_loan'] < 0, 'max_allowed_loan'] = None
df_partb.loc[df_partb['max_allowed_loan'] > 180000, 'max_allowed_loan'] = None
df_partb = df_partb.dropna(subset=['max_allowed_loan'])
df_partb['max_allowed_loan'] = df_partb['max_allowed_loan'].astype('int64')

"""Part(B)-Task(1) - Domain Understanding: Regression"""

df_partb['loan_approval_status'].value_counts()

df_partb_reg = df_partb[df_partb['loan_approval_status'] == 0].copy()

reg_columns = [
    'age',
    'income',
    'home_ownership',
    'emplyment_length',
    'loan_intent',
    'loan_amount',
    'loan_interest_rate',
    'loan_income_ratio',
    'payment_default_on_file',
    'credit_history_length',
    'max_allowed_loan'
]

df_partb_reg = df_partb_reg[reg_columns]

df_partb_reg.shape

df_partb_reg[reg_columns].columns.tolist()

df_partb_reg.to_csv("df_partb_reg_cleaned.csv", index=False)

"""Part(B)-Task(2) – Data Understanding: Producing Your Experimental Design

*   Numeric Variables
"""

df_partb_reg['age'].hist()
plt.title('Histogram of age')
plt.show()

df_partb_reg['income'].hist()
plt.title('Histogram of income')
plt.show()

df_partb_reg['loan_amount'].hist()
plt.title('Histogram of loan_amount')
plt.show()

df_partb_reg['loan_interest_rate'].hist()
plt.title('Histogram of loan_interest_rate')
plt.show()

df_partb_reg['loan_income_ratio'].hist()
plt.title('Histogram of loan_income_ratio')
plt.show()

df_partb_reg['credit_history_length'].hist()
plt.title('Histogram of credit_history_length')
plt.show()

df_partb_reg['max_allowed_loan'].hist()
plt.title('Histogram of max_allowed_loan')
plt.show()

import plotly.express as px

Spending_Score_fig = px.box(df_partb_reg, x='max_allowed_loan')
Spending_Score_fig.show()

"""

*   Categorial Variables

"""

df_partb_reg['home_ownership'].value_counts().plot(kind='bar')
plt.xlabel('home_ownership')
plt.ylabel('frequency')
plt.title('Bar chart of home_ownership')
plt.show()

df_partb_reg['emplyment_length'].value_counts().plot(kind='bar')
plt.xlabel('emplyment_length')
plt.ylabel('frequency')
plt.title('Bar chart of emplyment_length')
plt.show()

df_partb_reg['loan_intent'].value_counts().plot(kind='bar')
plt.xlabel('loan_intent')
plt.ylabel('frequency')
plt.title('Bar chart of loan_intent')
plt.show()

df_partb_reg['payment_default_on_file'].value_counts().plot(kind='bar')
plt.xlabel('payment_default_on_file')
plt.ylabel('frequency')
plt.title('Bar chart of payment_default_on_file')
plt.show()

"""Part(B)-Task(3) – Data Preprocessing: Transforming your data

"""

df_partb_reg.describe()

"""Part(B)-Task(4) – Modelling: Build Predictive Regression Models

(b)(ii)
"""

numeric_features = [
    'age',
    'income',
    'loan_amount',
    'loan_interest_rate',
    'loan_income_ratio',
    'credit_history_length'
]

all_features = [
    'age',
    'income',
    'home_ownership',
    'emplyment_length',
    'loan_intent',
    'loan_amount',
    'loan_interest_rate',
    'loan_income_ratio',
    'payment_default_on_file',
    'credit_history_length'
]

y = df_partb_reg['max_allowed_loan']

"""DT1 Model"""

X1 = df_partb_reg[numeric_features]

from sklearn.model_selection import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(
    X1, y, test_size=0.20, random_state=25
)

X1_train.shape, X1_test.shape, y1_train.shape, y1_test.shape

"""DT2 Model"""

X2 = df_partb_reg[all_features]

X2_train, X2_test, y2_train, y2_test = train_test_split(
    X2, y, test_size=0.20, random_state=25
)

X2_train.shape, X2_test.shape, y2_train.shape, y2_test.shape

"""Decision Tree"""

from sklearn.tree import DecisionTreeRegressor

dt1_model = DecisionTreeRegressor(random_state=14)
dt1_model.fit(X1_train, y1_train)

dt2_model = DecisionTreeRegressor(random_state=14)
dt2_model.fit(X2_train, y2_train)

"""Part(B)-Task(5) – Evaluation: How good are your models

(a)
"""

y1_pred = dt1_model.predict(X1_test)
y2_pred = dt2_model.predict(X2_test)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

"""DT1"""

mse_dt1 = mean_squared_error(y1_test, y1_pred)
print("DT1 MSE:", mse_dt1)

mae_dt1 = mean_absolute_error(y1_test, y1_pred)
print("DT1 MAE:", mae_dt1)

r2_dt1  = r2_score(y1_test, y1_pred)
print("DT1 R-Square:", r2_dt1)

"""DT2"""

mse_dt2 = mean_squared_error(y2_test, y2_pred)
print("DT2 MSE:", mse_dt2)

mae_dt2 = mean_absolute_error(y2_test, y2_pred)
print("DT2 MAE:", mae_dt2)

r2_dt2  = r2_score(y2_test, y2_pred)
print("DT2 R-Square:", r2_dt2)

"""(d)"""

from sklearn.tree import DecisionTreeRegressor

dt1_pruned = DecisionTreeRegressor(max_depth=4, random_state=14)
dt1_pruned.fit(X1_train, y1_train)

y1_pruned_pred = dt1_pruned.predict(X1_test)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse_pruned = mean_squared_error(y1_test, y1_pruned_pred)
print("Pruned DT1 (max_depth=4) MSE:", mse_pruned)

mae_pruned = mean_absolute_error(y1_test, y1_pruned_pred)
print("Pruned DT1 (max_depth=4) MAE:", mae_pruned)

r2_pruned = r2_score(y1_test, y1_pruned_pred)
print("Pruned DT1 (max_depth=4) R-Square:", r2_pruned)

from sklearn import tree
import matplotlib.pyplot as plt

plt.figure(figsize=(30,15))
tree.plot_tree(dt1_pruned,
               feature_names=X1_train.columns,
               filled=True,
               rounded=True,
               fontsize=8)
plt.show()

"""(e)"""

import pandas as pd

client_data = pd.DataFrame({
    'age': [56],
    'income': [57000],
    'loan_amount': [25700],
    'loan_interest_rate': [23],
    'loan_income_ratio': [10],
    'credit_history_length': [35]
})

predicted_max_loan = dt1_pruned.predict(client_data)
print("Predicted Maximum Loan Amount for Client 60256:", predicted_max_loan[0])